/*
 * Copyright 2021 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.jambalaya.example.jooq.tables.records;

import com.jambalaya.example.jooq.enums.PaymentMethodCardBrand;
import com.jambalaya.example.jooq.tables.PaymentMethod;
import edu.umd.cs.findbugs.annotations.NonNull;
import edu.umd.cs.findbugs.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PaymentMethodRecord extends UpdatableRecordImpl<PaymentMethodRecord>
        implements Record9<Long, LocalDateTime, LocalDateTime, Long, String, PaymentMethodCardBrand, LocalDate, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>payment_method.id</code>.
     */
    public PaymentMethodRecord setId(@NonNull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.id</code>.
     */
    @NonNull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>payment_method.created_date</code>.
     */
    public PaymentMethodRecord setCreatedDate(@NonNull LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.created_date</code>.
     */
    @NonNull
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>payment_method.last_modified_date</code>.
     */
    public PaymentMethodRecord setLastModifiedDate(@NonNull LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.last_modified_date</code>.
     */
    @NonNull
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>payment_method.version</code>.
     */
    public PaymentMethodRecord setVersion(@NonNull Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.version</code>.
     */
    @NonNull
    public Long getVersion() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>payment_method.stripe_payment_method_id</code>.
     */
    public PaymentMethodRecord setStripePaymentMethodId(@NonNull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.stripe_payment_method_id</code>.
     */
    @NonNull
    public String getStripePaymentMethodId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>payment_method.card_brand</code>.
     */
    public PaymentMethodRecord setCardBrand(@Nullable PaymentMethodCardBrand value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.card_brand</code>.
     */
    @Nullable
    public PaymentMethodCardBrand getCardBrand() {
        return (PaymentMethodCardBrand) get(6);
    }

    /**
     * Setter for <code>payment_method.card_expiration_date</code>.
     */
    public PaymentMethodRecord setCardExpirationDate(@Nullable LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.card_expiration_date</code>.
     */
    @Nullable
    public LocalDate getCardExpirationDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>payment_method.card_number</code>.
     */
    public PaymentMethodRecord setCardNumber(@Nullable String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.card_number</code>.
     */
    @Nullable
    public String getCardNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>payment_method.card_holder_name</code>.
     */
    public PaymentMethodRecord setCardHolderName(@Nullable String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>payment_method.card_holder_name</code>.
     */
    @Nullable
    public String getCardHolderName() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NonNull
    public Row9<Long, LocalDateTime, LocalDateTime, Long, String, PaymentMethodCardBrand, LocalDate, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    @NonNull
    public Row9<Long, LocalDateTime, LocalDateTime, Long, String, PaymentMethodCardBrand, LocalDate, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    @NonNull
    public Field<Long> field1() {
        return PaymentMethod.PAYMENT_METHOD.ID;
    }

    @Override
    @NonNull
    public Field<LocalDateTime> field2() {
        return PaymentMethod.PAYMENT_METHOD.CREATED_DATE;
    }

    @Override
    @NonNull
    public Field<LocalDateTime> field3() {
        return PaymentMethod.PAYMENT_METHOD.LAST_MODIFIED_DATE;
    }

    @Override
    @NonNull
    public Field<Long> field4() {
        return PaymentMethod.PAYMENT_METHOD.VERSION;
    }

    @Override
    @NonNull
    public Field<String> field5() {
        return PaymentMethod.PAYMENT_METHOD.STRIPE_PAYMENT_METHOD_ID;
    }

    @Override
    @NonNull
    public Field<PaymentMethodCardBrand> field6() {
        return PaymentMethod.PAYMENT_METHOD.CARD_BRAND;
    }

    @Override
    @NonNull
    public Field<LocalDate> field7() {
        return PaymentMethod.PAYMENT_METHOD.CARD_EXPIRATION_DATE;
    }

    @Override
    @NonNull
    public Field<String> field8() {
        return PaymentMethod.PAYMENT_METHOD.CARD_NUMBER;
    }

    @Override
    @NonNull
    public Field<String> field9() {
        return PaymentMethod.PAYMENT_METHOD.CARD_HOLDER_NAME;
    }

    @Override
    @NonNull
    public Long component1() {
        return getId();
    }

    @Override
    @NonNull
    public LocalDateTime component2() {
        return getCreatedDate();
    }

    @Override
    @NonNull
    public LocalDateTime component3() {
        return getLastModifiedDate();
    }

    @Override
    @NonNull
    public Long component4() {
        return getVersion();
    }

    @Override
    @NonNull
    public String component5() {
        return getStripePaymentMethodId();
    }

    @Override
    @Nullable
    public PaymentMethodCardBrand component6() {
        return getCardBrand();
    }

    @Override
    @Nullable
    public LocalDate component7() {
        return getCardExpirationDate();
    }

    @Override
    @Nullable
    public String component8() {
        return getCardNumber();
    }

    @Override
    @Nullable
    public String component9() {
        return getCardHolderName();
    }

    @Override
    @NonNull
    public Long value1() {
        return getId();
    }

    @Override
    @NonNull
    public LocalDateTime value2() {
        return getCreatedDate();
    }

    @Override
    @NonNull
    public LocalDateTime value3() {
        return getLastModifiedDate();
    }

    @Override
    @NonNull
    public Long value4() {
        return getVersion();
    }

    @Override
    @NonNull
    public String value5() {
        return getStripePaymentMethodId();
    }

    @Override
    @Nullable
    public PaymentMethodCardBrand value6() {
        return getCardBrand();
    }

    @Override
    @Nullable
    public LocalDate value7() {
        return getCardExpirationDate();
    }

    @Override
    @Nullable
    public String value8() {
        return getCardNumber();
    }

    @Override
    @Nullable
    public String value9() {
        return getCardHolderName();
    }

    @Override
    @NonNull
    public PaymentMethodRecord value1(@NonNull Long value) {
        setId(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value2(@NonNull LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value3(@NonNull LocalDateTime value) {
        setLastModifiedDate(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value4(@NonNull Long value) {
        setVersion(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value5(@NonNull String value) {
        setStripePaymentMethodId(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value6(@Nullable PaymentMethodCardBrand value) {
        setCardBrand(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value7(@Nullable LocalDate value) {
        setCardExpirationDate(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value8(@Nullable String value) {
        setCardNumber(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord value9(@Nullable String value) {
        setCardHolderName(value);
        return this;
    }

    @Override
    @NonNull
    public PaymentMethodRecord values(
            @NonNull Long value1, @NonNull LocalDateTime value2, @NonNull LocalDateTime value3, @NonNull Long value4,
            @NonNull String value5, @Nullable PaymentMethodCardBrand value6, @Nullable LocalDate value7,
            @Nullable String value8, @Nullable String value9
    ) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentMethodRecord
     */
    public PaymentMethodRecord() {
        super(PaymentMethod.PAYMENT_METHOD);
    }

    /**
     * Create a detached, initialised PaymentMethodRecord
     */
    public PaymentMethodRecord(
            @NonNull Long id, @NonNull LocalDateTime createdDate, @NonNull LocalDateTime lastModifiedDate,
            @NonNull Long version, @NonNull String stripePaymentMethodId, @Nullable PaymentMethodCardBrand cardBrand,
            @Nullable LocalDate cardExpirationDate, @Nullable String cardNumber, @Nullable String cardHolderName
    ) {
        super(PaymentMethod.PAYMENT_METHOD);

        setId(id);
        setCreatedDate(createdDate);
        setLastModifiedDate(lastModifiedDate);
        setVersion(version);
        setStripePaymentMethodId(stripePaymentMethodId);
        setCardBrand(cardBrand);
        setCardExpirationDate(cardExpirationDate);
        setCardNumber(cardNumber);
        setCardHolderName(cardHolderName);
    }

}
