name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up mise
        uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5
      - name: Spotless Check
        run: ./gradlew spotlessCheck
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
